// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrnhdbldaxhiskxfjzpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxybmhkYmxkYXhoaXNreGZqenB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDgxMjMsImV4cCI6MjA2NzI4NDEyM30.vnSL4uR7gVLoYBcH089TU42c_J9tnLCpv3zRZumF_gI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});