// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svmjtuqdwjofttmtjddn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2bWp0dXFkd2pvZnR0bXRqZGRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyOTM4OTcsImV4cCI6MjA3Njg2OTg5N30.TEmaqh62CEDdEFDePRaOuZaMV8cgdyXMXt5jl1bdF0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
